dynamic-layers: optee: add imx91/93 machines to compatible
Add all i.MX91/93 machines to COMPATIBLE_MACHINES for optee recipes.

This fixes the following build error:

  ERROR: Nothing PROVIDES 'optee-os'
  optee-os was skipped: incompatible with machine phyboard-nash-imx93-1 (not in COMPATIBLE_MACHINE)
  optee-os was skipped: incompatible with machine phyboard-nash-imx93-1 (not in COMPATIBLE_MACHINE)
  optee-os was skipped: incompatible with machine phyboard-nash-imx93-1 (not in COMPATIBLE_MACHINE)
  optee-os was skipped: incompatible with machine phyboard-nash-imx93-1 (not in COMPATIBLE_MACHINE)
  ERROR: Required build target 'phytec-qt6demo-image' has no buildable providers.
  Missing or unbuildable dependency chain was: ['phytec-qt6demo-image', 'imx-boot', 'optee-os']

Signed-off-by: Primoz Fiser <primoz.fiser@norik.com>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>