FROMGIT: libubootenv: fix multilib build
In case of multilib, the do_package fails with:

ERROR: libubootenv-0.2-r0 do_package: QA Issue: libubootenv: Files/directories were installed but not shipped in any package:
  /usr/lib/libubootenv.so
  /usr/lib/libubootenv.so.0.2

Issue is fixed in libubootenv repo - this patch updates SRCREV to the
commit with the fix.

Signed-off-by: Stefano Babic <sbabic@denx.de>
Reported-by: ChenQi <Qi.Chen@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry-picked from commit 9e21387ba2bd
git.openembedded.org/openembedded-core master)
Signed-off-by: Martin Schwan <m.schwan@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>