classes: uboot-extra-env: Handle UBOOT_CONFIG builds
do_apply_extra_env reads .config from ${B}, which only exists for
plain UBOOT_MACHINE builds. Iterate over all build dirs instead.

When generating multiple bootloader binaries, we see:

  ERROR: do_apply_extra_env: uboot-extra-env: u-boot-phytec/2026.01-phy1/build/.config not found - did do_configure run?

Fixes:
  398bb0d035ae ("classes: uboot-extra-env: Switch to u-boot's .env file mechanism")

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Tested-by: Leonard Anderweit <l.anderweit@phytec.de>
Signed-off-by: Martin Schwan <m.schwan@phytec.de>