dynamic-layers: freescale: Remove imx-atf_2.4 bbappend
The meta-freescale layer updated its imx-atf recipe version to 2.6. We
need to remove the 2.4 bbappend since there is no matching recipe
anymore.

Fixes following build error:
ERROR: No recipes in default available for:
  /home/riedmueller/yocto/yocto-master-imx8mm/sources/poky/../meta-phytec/dynamic-layers/freescale-layer/recipes-bsp/imx-atf/imx-atf_2.4.bbappend

Signed-off-by: Stefan Riedmueller <s.riedmueller@phytec.de>
Signed-off-by: Norbert Wesp <n.wesp@phytec.de>