scripts: switch_machine: Throw assertion if machine is not found.
By now if we have a machine in the manifest, but it is missing in
meta-phytec we get:

description = lambda x: self.src.machines[x]['DESCRIPTION'].split(',',1)
AttributeError: 'Vividict' object has no attribute 'split

replace this with more meaningful error message.

Signed-off-by: Jan Remmet <j.remmet@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>