kas: poky-upstream-k3: Add meta-ti again
Since commit aab2ddc8b ("recipes-bsp: ti-firmware: Drop in-layer
firmware recipes") nothing provides ti-sci-fw and ti-dm-fw anymore,
which u-boot-phytec-ti depends on for phyboard-lyra-am62xx-3:

  ERROR: Nothing PROVIDES 'ti-sci-fw' (but u-boot-phytec_2026.01-phy2.bb
  DEPENDS on or otherwise requires it)

Add meta-ti-bsp back so the firmware recipes are provided by meta-ti.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>