conf: templates: local.conf: Split licenses directory per multiconfig
With commit 7ebbd68f0fb2 ("license/license_image: Fix license file
layout to avoid overlapping files") we are no longer able to override
license files in deploy/licenses.
In our TI builds we are sharing the same deploy directory for
R5 and A53 builds. Their native-classes deploy identical license files
which leads to build failures.

  ERROR: mc:k3r5:mpfr-native-4.2.1-r0 do_populate_lic_setscene: Recipe mpfr-native is trying to install files into a shared area when those files already exist.

Let's simply split the licenses directory into subdirectories per
used multiconfig. This split affects only native packages.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>