scripts: switch_machine: Fallback to UNASSIGNED for emtpy build list
Yocto builds that do not support any builds by "SUPPORTEDIMAGE" will throw
the following error:

Traceback (most recent call last):
  File "./sources/meta-phytec/scripts/switch_machine.py", line 103, in <module>
    main()
  File "./sources/meta-phytec/scripts/switch_machine.py", line 98, in main
    if not bsp.switch_machine(args.machine, args.distro):
  File "./sources/meta-phytec/scripts/switch_machine.py", line 27, in switch_machine
    min_len_machines = min(len(build[0]) for build in builds)
ValueError: min() arg is an empty sequence

Instead of crashing it is better to do nothing and keep the machine
as "UNASSIGNED". Maybe this can be handled properly by the phylib.py with a
dummy supported_build that gets selected if we have no builds at all.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>