conf: phyk3: Do not set INITRAMFS_IMAGE
Setting INITRAMFS_IMAGE is a hard dependency to meta-ampliphy and
makes our non-ampliphy KAS builds fail:

  ERROR: Nothing PROVIDES 'phytec-initramfs-image'
  ERROR: Required build target 'core-image-base' has no buildable providers.
  Missing or unbuildable dependency chain was: ['core-image-base', 'virtual/kernel', 'phytec-initramfs-image']

As noted in commit 8940e4a419 ("recipes-kernel: linux-phytec-ti_6.12
Drop obsolete config fragments") we do not want to have INITRAMFS_IMAGE
set by machine configuration.

Let us move this configuration to ampliphy.conf.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>