classes: fsl-bin-unpack: Remove update_data
update_data was removed in poky commit d8e9ee8fd5 (bitbake:
data/data_smart/build: Clean up datastore finalize/update_data references) and
has been a no-op before that.

Fixes:
ERROR: firmware-imx-5.4-r0 do_unpack: Error executing a python function in
exec_func_python() autogenerated:
Exception: AttributeError: module 'bb.data' has no attribute 'update_data'

Signed-off-by: Leonard Anderweit <l.anderweit@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>