recipes-kernel: linux-phytec-ti: Set KERNEL_VERSION_SANITY_SKIP = "1"
With poky commit 2186202022d1 ("glibc: stable 2.39 branch updates.") we can see
the following errors when building linux-phytec-ti RT builds:

ERROR: phytec-headless-image-1.0-r0 do_rootfs: Could not invoke dnf.
[...]
package packagegroup-cryptodev-1.0-r0.noarch from oe-repo requires cryptodev-module, but none of the providers can be installed
  - package cryptodev-module-1.14-r0.phyboard_lyra_am62xx_3 from oe-repo requires kernel-module-cryptodev-6.6.32-rt32-gff957b44-ge0905559f01f, but none of the providers can be installed
  - conflicting requests
  - nothing provides kernel-6.6.32-rt32-gff957b44-ge0905559f01f needed by kernel-module-cryptodev-6.6.32-rt32-gff957b44-ge0905559f01f-1.14-r0.phyboard_lyra_am62xx_3 from oe-repo

Fix the errors by adding KERNEL_VERSION_SANITY_SKIP = 1 as we do in our other recipes.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>