conf: machine: k3: disable initramfs fitImage for update to fix dep loop
Do not build fitImage with initramFS in for update cases.
Unset INITRAMFS_IMAGE for the update case to break a circular dependency
between the kernel, initramfs image, and partup.

Fixes:
  ERROR: 6742 unbuildable tasks were found
  These are usually caused by circular dependencies and any circular dependency chains
  found will be printed below. Increase the debug level to see a list of unbuildable tasks.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>