conf: machine: phyk3: Add fitImage deploy dependency for wic
Make do_image_wic depend on linux-yocto-fitimage:do_deploy.

Fixes:

  ERROR: phytec-provisioning-image-1.0-r0 do_image_wic:
  ...
  cannot stat '...deploy-securiphy-provisioning/images/phyboard-lyra-am62xx-4/fitImage': No such file or directory
  ...

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>